// src/pages/auth/Login.jsx
import { useState } from "react";

import axios from "axios";
import Cookies from "js-cookie";
import validator from "validator";

import decryptPersonalPrivateKey from "../../../functions/decrypt-personal-private-key";

function App() {
  const [error, setError] = useState(false);

  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  async function login() {
    if (validator.isEmpty(username) === true) {
      setError("Username can not be empty");
      return;
    }

    if (validator.isEmpty(password) === true) {
      setError("Password can not be empty");
      return;
    }

    const json = { username: username, password: password };
    await axios.post("/api/auth/login", json).then((response) => {
      if (response.data.token) {
        Cookies.set("token", response.data.token, {
          expires: 180,
          sameSite: "strict",
        });
        Cookies.set("username", response.data.username, {
          expires: 180,
          sameSite: "strict",
        });
        Cookies.set("id", response.data.id, {
          expires: 180,
          sameSite: "strict",
        });
        decryptPersonalPrivateKey(response.data.private_key, password).then(
          (result) => {
            window.sessionStorage.setItem("private_key", result);
          }
        );
        window.location.href = "/";
      } else {
        setError(response.data.error);
      }
    });
  }

  return (
    <>
      <div className="flex flex-col min-h-screen justify-center items-center">
        <div className="form-control w-full max-w-xs mt-8">
          <label className="label">
            <span className="label-text">What is your username?</span>
          </label>
          <input
            type="username"
            placeholder="Enter your username"
            className="input input-bordered input-secondary w-full max-w-xs"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
          />
        </div>
        <div className="form-control w-full max-w-xs mt-5">
          <label className="label">
            <span className="label-text">Now enter your password</span>
            <span className="label-text-alt">
              <a href="/recover-send">Forgot?</a>
            </span>
          </label>
          <input
            type="password"
            placeholder="Your password"
            className="input input-bordered input-secondary w-full max-w-xs"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
        </div>
        <div className="form-control w-full max-w-xs mt-9">
          <button
            className="capitalize btn btn-outline w-full"
            onClick={() => login()}
          >
            login
          </button>
        </div>
        <div className="form-control w-full max-w-xs mt-4">
          <a href="/register" className="capitalize btn btn-ghost w-full">
            register
          </a>
        </div>
      </div>

      <div className="toast toast-bottom toast-end z-50">
        {error && (
          <div
            className="alert alert-error hover:bg-red-900 cursor-pointer border-0"
            onClick={() => setError(null)}
          >
            <span>{error}</span>
          </div>
        )}
      </div>
    </>
  );
}

export default App;

// src/routes/login/+page.svelte
<script>
  import Alert from "../../components/alert.svelte";

  import Cookies from "js-cookie";

  let username = "";
  let password = "";

  let loading = false;

  let field = "";
  let message = "";

  import makePostRequest from "$lib/other/make-post-request";
  import decryptPersonalPrivateKey from "$lib/encryption/decrypt-personal-private-key";

  async function login() {
    loading = true;
    await makePostRequest("/api/auth/login", {
      username: username,
      password: password,
    }).then((response) => {
      if (response.error === true) {
        field = response.fields[0];
        message = response.data;
      } else {
        console.log(response);
        field = "";
        message = "";

        Cookies.set("token", response.token, {
          expires: 180,
          sameSite: "strict",
        });

        decryptPersonalPrivateKey(response.private_key, password).then(
          (result) => {
            window.sessionStorage.setItem("private_key", result);
          }
        );

        window.location.href = "/";
      }
    });

    loading = false;
  }
</script>

<div class="flex flex-col min-h-screen justify-center items-center">
  <div class="form-control w-full max-w-xs">
    <label class="label" for="">
      <span class="label-text">What is your username?</span>
    </label>
    <input
      type="username"
      placeholder="Enter your username"
      class="input input-bordered w-full max-w-xs border-red"
      bind:value={username}
    />
  </div>

  <div class="form-control w-full max-w-xs mt-3">
    <label class="label" for="">
      <span class="label-text">Now enter your password</span>
      <a class="label-text-alt underline" href="/reset-password">Forgot?</a>
    </label>
    <input
      type="password"
      placeholder="Enter your password"
      class="input input-bordered w-full max-w-xs"
      bind:value={password}
    />
  </div>

  <div class="form-control w-full max-w-xs mt-7">
    <button
      class="btn btn-outline capitalize"
      on:click={login}
      disabled={loading}
    >
      {#if loading}
        <span class="loading loading-spinner opacity-50" />
      {:else}
        Login
      {/if}
    </button>
  </div>

  <div class="form-control w-full max-w-xs mt-3">
    <button
      class="btn btn-ghost capitalize"
      on:click={() => (window.location.href = "/register")}
    >
      Register
    </button>
  </div>

  <Alert {message} {field} />
</div>
